### ISSUE TITLE
Adding a video in to the readme?

### ISSUE THREAD

**Issue by ArthurSonzogni** [tusharpm/tiles#2]
It would be great adding a video of the game.

Maybe as mp4:
```
https://user-images.githubusercontent.com/4759106/152344330-c688251b-e144-4017-bbb5-71b269b5804c.mp4
```

https://user-images.githubusercontent.com/4759106/152344330-c688251b-e144-4017-bbb5-71b269b5804c.mp4

Or as a GIF:
```
![ezgif com-gif-maker](https://user-images.githubusercontent.com/4759106/152344137-42e991d1-f840-447c-a690-cd0347bedc3b.gif)
```
Giving:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/4759106/152344137-42e991d1-f840-447c-a690-cd0347bedc3b.gif)

**Comment by tusharpm** [comment]
Added in 64ce6c5b67701bea059795f2addfaad755d4b610.

Thanks for the GIF! I was playing with [asciinema](https://asciinema.org/a/3Qhf2o4DU5AoVUjk9AVk61bWU) earlier for the same but it had a rendering error for bright colors.
